### ISSUE TITLE
咨询关于论文中图二的实验结果

### ISSUE THREAD

**Issue by rain2050** [RuixiangXue/NeRI#2]
您好，

感谢您开源优秀的工作，再复现您的代码过程中，执行Testing命令后，得到的实验结果如表格所示，
但是在您论文中的图2所示，D1 PSNR大概是在29-35之间，但是我得到的实验结果最大才29.68。您知道这是什么原因造成的吗？

期待您的回复。

![image](https://github.com/RuixiangXue/NeRI/assets/39472362/410eca30-35aa-4dec-b896-f24e4888b087)
![image](https://github.com/RuixiangXue/NeRI/assets/39472362/9e3c3eca-b019-4f02-80b9-4911e2f35260)

**Comment by RuixiangXue** [comment]
Thank you for your interest in our work. This may be related to subtle differences in the legacy code (a cpp interface). We are comparing the different versions of NeRI and will soon update and provide a download link for the trained model for evaluation.

**Comment by rain2050** [comment]
期待您的更新，感谢您的回复。

**Comment by mmyy521** [comment]
> 您好，
> 
> 感谢您开源优秀的工作，再复现您的代码过程中，执行Testing命令后，得到的实验结果如表格所示， 但是在您论文中的图2所示，D1 PSNR大概是在29-35之间，但是我得到的实验结果最大才29.68。您知道这是什么原因造成的吗？
> 
> 期待您的回复。
> 
> ![image](https://github.com/RuixiangXue/NeRI/assets/39472362/410eca30-35aa-4dec-b896-f24e4888b087) ![image](https://github.com/RuixiangXue/NeRI/assets/39472362/9e3c3eca-b019-4f02-80b9-4911e2f35260)

您好，感谢您的分享，请问您训练的数据是包括SemanticKITTI序列中的多少呢？我使用序列00训练600 epochs的结果PSNR D1和D2都达不到30，想请问您一下是否是训练集数据量少的原因，十分感谢。
